In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [81]:
df_train=pd.read_csv('train.csv')
df_test=pd.read_csv('test.csv')
df_train

RowNumber  CustomerId     Surname  CreditScore Geography  Gender  Age  \
0           551    15806307   Trevisano          720     Spain    Male   38   
1          6897    15709621      Martin          682    France  Female   54   
2          4588    15619340      Palmer          672    France  Female   31   
3           291    15620746  Napolitani          592     Spain  Female   40   
4          1673    15646372         Yao          753     Spain    Male   42   
...         ...         ...         ...          ...       ...     ...  ...   
7995       5345    15584532          Yu          568    France  Female   35   
7996       5837    15606641        Liao          602   Germany  Female   45   
7997       7335    15739692       Ferri          679     Spain  Female   43   
7998       9552    15791373     Worsnop          715    France    Male   38   
7999        178    15739931      Ibekwe          600    France  Female   42   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          5  114051.97              2          0               1   
1          4   62397.41              1          1               0   
2          5  119903.67              1          1               1   
3          4  104257.86              1          1               0   
4          5  120387.73              1          0               1   
...      ...        ...            ...        ...             ...   
7995       6  121079.60              2          1               1   
7996       7  145846.07              1          1               0   
7997       5  132810.01              1          1               0   
7998       4  118729.45              1          0               0   
7999       5   62397.41              1          0               0   

      EstimatedSalary  Exited  
0           107577.29       0  
1           113088.60       1  
2           132925.17       0  
3           110857.33       0  
4           126378.57       0  
...               ...     ...  
7995        124890.50       1  
7996         99276.02       0  
7997        130780.85       1  
7998         95484.52       0  
7999         66315.00       0  

[8000 rows x 14 columns]

In [82]:
#資料預處理，刪掉不影響預測結果的特徵
df_train=df_train.drop(columns=['RowNumber','CustomerId','Surname'])
#將類別型資料編碼
df_train['Geography'] = df_train['Geography'].replace(['France', 'Germany', 'Spain'], [0, 1, 2])
df_train['Gender'] = df_train['Gender'].replace(['Male', 'Female'], [0, 1])
df_train

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             720          2       0   38       5  114051.97              2   
1             682          0       1   54       4   62397.41              1   
2             672          0       1   31       5  119903.67              1   
3             592          2       1   40       4  104257.86              1   
4             753          2       0   42       5  120387.73              1   
...           ...        ...     ...  ...     ...        ...            ...   
7995          568          0       1   35       6  121079.60              2   
7996          602          1       1   45       7  145846.07              1   
7997          679          2       1   43       5  132810.01              1   
7998          715          0       0   38       4  118729.45              1   
7999          600          0       1   42       5   62397.41              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             0               1        107577.29       0  
1             1               0        113088.60       1  
2             1               1        132925.17       0  
3             1               0        110857.33       0  
4             0               1        126378.57       0  
...         ...             ...              ...     ...  
7995          1               1        124890.50       1  
7996          1               0         99276.02       0  
7997          1               0        130780.85       1  
7998          0               0         95484.52       0  
7999          0               0         66315.00       0  

[8000 rows x 11 columns]

In [83]:
#資料預處理，刪掉不影響預測結果的特徵
df_test=df_test.drop(columns=['RowNumber','CustomerId','Surname'])
#將類別型資料編碼
df_test['Geography'] = df_test['Geography'].replace(['France', 'Germany', 'Spain'], [0, 1, 2])
df_test['Gender'] = df_test['Gender'].replace(['Male', 'Female'], [0, 1])
df_test

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             726          0       1   39       3   62397.41              1   
1             661          0       0   42       3  130339.64              1   
2             545          0       0   34       6   62397.41              2   
3             731          2       1   42       3   86717.08              1   
4             533          0       1   50       6   62397.41              1   
...           ...        ...     ...  ...     ...        ...            ...   
1995          628          0       0   35       6   62397.41              2   
1996          639          1       0   41       5   98154.30              2   
1997          548          0       1   46       3  119078.34              2   
1998          602          2       1   44       7   62397.41              2   
1999          615          1       1   32       5  105570.37              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             0               0        106139.31  
1             1               0        125776.38  
2             1               1         78372.28  
3             1               0        136026.27  
4             1               1        135205.58  
...         ...             ...              ...  
1995          1               1         96201.09  
1996          1               0        109531.64  
1997          1               1        116725.67  
1998          1               1        128135.95  
1999          1               0        104140.30  

[2000 rows x 10 columns]

In [84]:
X_train=df_train.iloc[:,:df_train.shape[1]-1]
y_train=df_train.loc[:,['Exited']]
print(X_train)
print(y_train)

      CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             720          2       0   38       5  114051.97              2   
1             682          0       1   54       4   62397.41              1   
2             672          0       1   31       5  119903.67              1   
3             592          2       1   40       4  104257.86              1   
4             753          2       0   42       5  120387.73              1   
...           ...        ...     ...  ...     ...        ...            ...   
7995          568          0       1   35       6  121079.60              2   
7996          602          1       1   45       7  145846.07              1   
7997          679          2       1   43       5  132810.01              1   
7998          715          0       0   38       4  118729.45              1   
7999          600          0       1   42       5   62397.41              1   

      HasCrCard  IsActiveMember  EstimatedSalary  


In [85]:
from sklearn.preprocessing import MinMaxScaler 
X_train=X_train.values
scaler = MinMaxScaler(feature_range=(0, 1))
scaled = scaler.fit_transform(X_train)
print(scaled)
scaled.shape[0],scaled.shape[1]

[[0.89250814 1.         0.         ... 0.         1.         0.58916275]
 [0.76872964 0.         1.         ... 1.         0.         0.65403228]
 [0.73615635 0.         1.         ... 1.         1.         0.88751378]
 ...
 [0.75895765 1.         1.         ... 1.         0.         0.86227459]
 [0.8762215  0.         0.         ... 0.         0.         0.44682775]
 [0.50162866 0.         1.         ... 0.         0.         0.10349504]]


(8000, 10)